/** UX-01 — shared portal UI primitives (accessible, token-only). */
export { Notice, ErrorBanner } from './feedback'
export { StatusBadge, statusTone, statusToneOrNeutral } from './status-badge'
export { Panel } from './panel'
export { ConfirmSubmit } from './confirm-submit'
export { LoadMore } from './load-more'
export { SubmitButton } from './submit-button'
export { IdempotencyField } from './idempotency-field'
export { AccessDenied } from './access-denied'
export { ClearStatusParam } from './clear-status-param'
export { AuditNote } from './audit-note'
// UIF-01 — token-bound presentation primitives (ADR 0016).
export { KpiStat } from './kpi-stat'
export type { StatTone } from './kpi-stat'
export { StatStrip } from './stat-strip'
export { SectionCard } from './section-card'
export { ContributionBar } from './contribution-bar'
export type { ContributionSegment } from './contribution-bar'
// UIF-01b — @visx chart primitives (ADR 0016 D2).
export { Gauge } from './gauge'
export { Sparkline } from './sparkline'
