// A record-and-replay double for the `kosli` binary (2.1.0, phase 2 prep; kosli-seam.md decision K8:
// unit tests pass without a Kosli org). `createFakeKosli(dir)` writes an executable `kosli` script
// into `dir`; point KOSLI_BIN at it (or put `dir` first on PATH) and every invocation is appended to
// `calls.jsonl` — argv, stdin, cwd, the instant — and answered from `responses.json`, a list of
// { match: ["attest", "generic"], stdout, stderr, exit } rules matched by argv prefix, first wins,
// default exit 0 with `{}`. `calls(dir)` reads the log back; `respond(dir, match, reply)` adds a
// rule; `reset(dir)` clears the log.
//
// The double proves two things the real binary cannot in CI: that a rejected envelope NEVER reaches
// the binary (the call log stays empty), and that what does reach it is exactly the argv and payload
// the harness meant to send. It proves nothing about Kosli itself — an integration run against a
// real org, recorded in docs/integration-run.md, is the only thing that does.
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export const CALLS_FILE = 'calls.jsonl';
export const RESPONSES_FILE = 'responses.json';

const SCRIPT = `#!/usr/bin/env node
// GENERATED by core/kosli-fake.mjs — a record-and-replay double for the kosli CLI. Not Kosli.
import { appendFileSync, existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const here = dirname(fileURLToPath(import.meta.url));
const argv = process.argv.slice(2);
let stdin = '';
try { if (!process.stdin.isTTY) stdin = readFileSync(0, 'utf8'); } catch { stdin = ''; }
appendFileSync(join(here, '${CALLS_FILE}'), JSON.stringify({ argv, stdin, cwd: process.cwd(), at: new Date().toISOString() }) + '\\n');
const rp = join(here, '${RESPONSES_FILE}');
const rules = existsSync(rp) ? JSON.parse(readFileSync(rp, 'utf8')) : [];
const rule = rules.find((r) => Array.isArray(r.match) && r.match.every((m, i) => argv[i] === m));
process.stdout.write(rule ? (rule.stdout ?? '') : '{}');
if (rule?.stderr) process.stderr.write(rule.stderr);
process.exit(typeof rule?.exit === 'number' ? rule.exit : 0);
`;

/** Write the fake into `dir` and return { bin, dir }. Idempotent. */
export function createFakeKosli(dir) {
  mkdirSync(dir, { recursive: true });
  const bin = join(dir, 'kosli');
  writeFileSync(bin, SCRIPT);
  chmodSync(bin, 0o755);
  if (!existsSync(join(dir, RESPONSES_FILE))) writeFileSync(join(dir, RESPONSES_FILE), '[]\n');
  if (!existsSync(join(dir, CALLS_FILE))) writeFileSync(join(dir, CALLS_FILE), '');
  return { bin, dir };
}

/** Every recorded invocation, oldest first. */
export function calls(dir) {
  const p = join(dir, CALLS_FILE);
  if (!existsSync(p)) return [];
  return readFileSync(p, 'utf8').split('\n').filter(Boolean).map((l) => JSON.parse(l));
}

/** Add a response rule: argv prefix → { stdout, stderr, exit }. Later rules never shadow earlier ones. */
export function respond(dir, match, { stdout = '', stderr = '', exit = 0 } = {}) {
  const p = join(dir, RESPONSES_FILE);
  const rules = existsSync(p) ? JSON.parse(readFileSync(p, 'utf8')) : [];
  rules.push({ match, stdout: typeof stdout === 'string' ? stdout : JSON.stringify(stdout), stderr, exit });
  writeFileSync(p, JSON.stringify(rules, null, 2) + '\n');
}

/** Clear the call log (the response table stays). */
export function reset(dir) { writeFileSync(join(dir, CALLS_FILE), ''); }
